DEFAULT_DIR_DATA = "data"
DEFAULT_DIR_SKILLS = "memory/skills"
DEFAULT_DIR_ASSETS = "memory/assets"

DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_OLLAMA_MODEL = "gemma4:latest"
DEFAULT_CODEX_MODEL = "gpt-5.2"

# Agent loop guardrails.
DEFAULT_MAX_ITERATIONS = 12
DEFAULT_OBSERVATION_MAX_CHARS = 12_000
DEFAULT_TRANSCRIPT_MAX_CHARS = 60_000

# Memory limits (unchanged from v4).
DEFAULT_MEMORY_FILE_MAX_BYTES = 128_000
DEFAULT_MEMORY_FILES_MAX = 5
DEFAULT_RENDERED_CONTEXT_MAX_CHARS = 80_000
ALLOWED_MEMORY_EXTENSIONS = (".md", ".txt")

# Codex CLI delegation (computer-use) defaults.
DEFAULT_CODEX_AGENT_TIMEOUT_SECONDS = 600
DEFAULT_CODEX_AGENT_SANDBOX = "workspace-write"
